name: Pre-commit Checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go_version
      - name: Check License
        run: make license-check
      - name: Set Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm install -g @angular/cli > /dev/null
          npm install -g pnpm > /dev/null
      - name: Install Dependencies
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 pnpm install
      - name: Build Prod
        run: pnpm build:prod
      - name: Test Coverage
        run: pnpm test:coverage
      - name: Go lint
        run: make lint
      - name: Go unit tests
        run: make test_go
      - name: Code coverage
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.txt
          # After codecov/codecov-action@v4, tokenless uploading of coverage files to non-public repo is unsupported.
          # To enable codecov analysis in your forked repo. Please configure CODECOV_TOKEN in your repository secrets.
          # Ref: https://docs.codecov.com/docs/adding-the-codecov-token
          token: ${{ secrets.CODECOV_TOKEN }}
