name: Pre-commit Checks

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check License
        run: make license-check
      - name: Set Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm install -g @angular/cli > /dev/null
          npm install -g yarn > /dev/null
      - name: Install Dependencies
        run: yarn install
      - name: Build Prod
        run: yarn build:prod
      - name: Test Coverage
        run: yarn test:coverage
